const crypto = require('crypto');
const { put, list } = require('@vercel/blob');
const seedEvents = require('../data/events.json');
const COOKIE = 'troop_admin';
const maxUploadBytes = 10 * 1024 * 1024;
function json(res, status, body, headers = {}) { res.statusCode = status; res.setHeader('Content-Type', 'application/json; charset=utf-8'); Object.entries(headers).forEach(([key, value]) => res.setHeader(key, value)); res.end(JSON.stringify(body)); }
function parseCookies(req) { return Object.fromEntries((req.headers.cookie || '').split(';').map(value => value.trim().split('=').map(decodeURIComponent)).filter(pair => pair[0])); }
function sign(value) { return crypto.createHmac('sha256', process.env.ADMIN_PASSWORD || '').update(value).digest('base64url'); }
function isAuthenticated(req) { const token = parseCookies(req)[COOKIE]; if (!token) return false; const [payload, signature] = token.split('.'); if (!payload || !signature || signature.length !== sign(payload).length) return false; if (!crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(sign(payload)))) return false; try { return JSON.parse(Buffer.from(payload, 'base64url').toString()).expires > Date.now(); } catch { return false; } }
function requireAuth(req, res) { if (isAuthenticated(req)) return true; json(res, 401, { error: 'Sign in required.' }); return false; }
async function readBody(req) { const chunks = []; let size = 0; for await (const chunk of req) { size += chunk.length; if (size > 14 * 1024 * 1024) throw Error('Request is too large.'); chunks.push(chunk); } return JSON.parse(Buffer.concat(chunks).toString() || '{}'); }
async function loadEvents() { const result = await list({ prefix: 'data/events.json', limit: 1 }); if (!result.blobs.length) { await saveEvents(seedEvents); return seedEvents; } const response = await fetch(result.blobs[0].url, { cache: 'no-store' }); if (!response.ok) throw Error('The event store could not be read.'); return response.json(); }
async function saveEvents(events) { await put('data/events.json', JSON.stringify(events), { access: 'public', contentType: 'application/json', allowOverwrite: true }); }
function sanitizeEvent(body, old = {}) { return { id: old.id || crypto.randomUUID(), date: String(body.date || '').slice(0, 16), title: String(body.title || '').trim().slice(0, 160), details: String(body.details || '').trim().slice(0, 4000), links: Array.isArray(body.links) ? body.links.filter(link => /^https?:\/\//i.test(link?.url || '')).map(link => ({ label: String(link.label || link.url).slice(0, 100), url: String(link.url) })) : [], attachments: Array.isArray(body.attachments) ? body.attachments : old.attachments || [] }; }
module.exports = async (req, res) => { const url = new URL(req.url, `https://${req.headers.host}`); const endpoint = url.searchParams.get('endpoint'); const pathname = endpoint ? '/api/' + endpoint : url.pathname; try { if (pathname === '/api/session' && req.method === 'GET') return json(res, 200, { authenticated: isAuthenticated(req) }); if (pathname === '/api/login' && req.method === 'POST') { const body = await readBody(req); if (body.username !== process.env.ADMIN_USERNAME || body.password !== process.env.ADMIN_PASSWORD) return json(res, 401, { error: 'Incorrect username or password.' }); const payload = Buffer.from(JSON.stringify({ expires: Date.now() + 8 * 60 * 60 * 1000 })).toString('base64url'); return json(res, 200, { ok: true }, { 'Set-Cookie': `${COOKIE}=${payload}.${sign(payload)}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=28800` }); } if (pathname === '/api/logout' && req.method === 'POST') return json(res, 200, { ok: true }, { 'Set-Cookie': `${COOKIE}=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0` }); if (pathname === '/api/events' && req.method === 'GET') return json(res, 200, await loadEvents()); if (pathname === '/api/uploads' && req.method === 'POST') { if (!requireAuth(req, res)) return; const body = await readBody(req), raw = String(body.data || '').replace(/^data:[^;]+;base64,/, ''), bytes = Buffer.from(raw, 'base64'); if (!raw || !bytes.length || bytes.length > maxUploadBytes) return json(res, 400, { error: 'Choose a file under 10 MB.' }); const name = String(body.name || 'attachment').replace(/[^a-zA-Z0-9._ -]/g, '_'); const blob = await put(`uploads/${Date.now()}-${name}`, bytes, { access: 'public', addRandomSuffix: true, contentType: String(body.type || 'application/octet-stream') }); return json(res, 201, { name, url: blob.url }); } if (pathname === '/api/events' && req.method === 'POST') { if (!requireAuth(req, res)) return; const event = sanitizeEvent(await readBody(req)); if (!event.date || !event.title) return json(res, 400, { error: 'Date and title are required.' }); const events = await loadEvents(); events.push(event); await saveEvents(events); return json(res, 201, event); } const match = pathname.match(/^\/api\/events\/([^/]+)$/); if (match && ['PUT', 'DELETE'].includes(req.method)) { if (!requireAuth(req, res)) return; const events = await loadEvents(), index = events.findIndex(event => event.id === match[1]); if (index < 0) return json(res, 404, { error: 'Event not found.' }); if (req.method === 'DELETE') { events.splice(index, 1); await saveEvents(events); return json(res, 200, { ok: true }); } const event = sanitizeEvent(await readBody(req), events[index]); if (!event.date || !event.title) return json(res, 400, { error: 'Date and title are required.' }); events[index] = event; await saveEvents(events); return json(res, 200, event); } return json(res, 404, { error: 'Not found.' }); } catch (error) { return json(res, 500, { error: error.message || 'Unable to process request.' }); } };


